CREATE TABLE  UYELER (
UYE_NO INT IDENTITY(1,1),
UYE_ADI VARCHAR(50),
UYE_SOYADI VARCHAR(20),
CINSIYET INT ,
ADRES_NO INT,
TELEFON VARCHAR(20),
EPOSTA VARCHAR(50),
PRIMARY KEY ("UYE_NO")
);  

ALTER TABLE UYELER
ADD CONSTRAINT FK_ADRESNO FOREIGN KEY(ADRES_NO) REFERENCES ADRESLER(ADRES_NO);

CREATE TABLE ADRESLER (
ADRES_NO INT IDENTITY(1,1),
CADDE VARCHAR(50),
MAHALLE VARCHAR(50),
BINA_NO INT ,
SEHIR VARCHAR(20),
POSTA_KODU INT,
ULKE VARCHAR(20)
PRIMARY KEY("ADRES_NO")
UYE_NO INT ,
);

ALTER TABLE ADRESLER
ADD CONSTRAINT FK_UYENO FOREIGN KEY(UYE_NO) REFERENCES UYELER(UYE_NO) ;

CREATE TABLE EMANET (
EMANET_NO INT,
ISBN VARCHAR(20) NOT NULL, 
UYE_NO INT NOT NULL,
KUTUPHANE_NO INT NOT NULL,
EMANET_TARIHI DATETIME ,
TESLIM_TARIHI DATETIME ,
PRIMARY KEY ("EMANET_NO")
);
 ALTER TABLE EMANET
ADD CONSTRAINT FK_UYENO FOREIGN KEY(UYE_NO) REFERENCES UYELER(UYE_NO); 

CREATE TABLE KITAPLAR (
ISBN VARCHAR(20) NOT NULL,
KITAP_ADI VARCHAR(50),
YAYIN_TARIHI DATETIME,
S_SAYISI INT,
EMANET_NO INT,
 PRIMARY KEY("ISBN")
);
ALTER TABLE KITAPLAR
ADD CONSTRAINT FK_EMANETNO FOREIGN KEY(EMANET_NO) REFERENCES EMANET(EMANET_NO);

CREATE TABLE YAZARLAR (
YAZAR_NO INT,
YAZAR_ADI VARCHAR(20),
YAZAR_SOYADI VARCHAR (20),
PRIMARY KEY("YAZAR_NO")
);




CREATE TABLE KATEGORI(
KATEGORI_NO INT IDENTITY(1,1),
KATEGORI_ADI VARCHAR(20),
PRIMARY KEY ("KATEGORI_NO")

);

CREATE TABLE KUTUPHANE (
KUTUPHANE_NO INT IDENTITY(1,1) NOT NULL,
ADRES_NO INT ,
KUTUPHANE_ISMI VARCHAR(20),
ACIKLAMA VARCHAR(50),
EMANET_NO INT,
PRIMARY KEY ("KUTUPHANE_NO"),
);

ALTER TABLE KUTUPHANE 
ADD CONSTRAINT FK_ADRESNO FOREIGN KEY(ADRES_NO) REFERENCES ADRESLER(ADRES_NO),
ADD CONSTRAINT FK_EMANETNO FOREIGN KEY(EMANET_NO) REFERENCES EMANET(EMANET_NO) ;


CREATE TABLE KITAP_KUTUPHANE  (
KUTUPHANE_NO INT NOT NULL,
ISBN VARCHAR(20) NOT NULL,
MIKTAR INT,

);


ALTER TABLE KITAP_KUTUPHANE
ADD CONSTRAINT FK_KUTUPHANENO FOREIGN KEY(KUTUPHANE_NO) REFERENCES KUTUPHANE(KUTUPHANE_NO);
ADD CONSTRAINT FK_ISBN FOREIGN KEY(ISBN) REFERENCES KITAPLAR(ISBN)

CREATE TABLE KITAP_KATEGORI(
ISBN VARCHAR(20),
KATEGORI_NO INT NOT NULL,

);

ALTER TABLE KITAP_KATEGORI
ADD CONSTRAINT FK_ISBN FOREIGN KEY (ISBN) REFERENCES KITAPLAR(ISBN)
ADD CONSTRAINT FK_KATEGORINO FOREIGN KEY (KATEGORI_NO) REFERENCES KATEGORI(KATEGORI_NO)

CREATE TABLE KITAP_YAZAR(
ISBN VARCHAR(20) NOT NULL,
YAZAR_NO INT NOT NULL,

);

ALTER TABLE KITAP_YAZAR
ADD CONSTRAINT FK_ISBN FOREIGN KEY(ISBN) REFERENCES KITAPLAR(ISBN)
ADD CONSTRAINT FK_YAZARNO FOREIGN KEY (YAZAR_NO) REFERENCES YAZARLAR(YAZAR_NO)

/* 2.ALISTIRMA EKLE,GUNCELLE,SÝL */

INSERT INTO UYELER (UYE_NO,UYE_ADI ,UYE_SOYADI, CINSIYET,ADRES_NO,TELEFON, EPOSTA )
VALUES('1', 'AYSE ','KARA','0','1','3561234556','aa@gmail.com');

 INSERT INTO ADRESLER(ADRES_NO,CADDE, MAHALLE,BINA_NO,SEHIR,POSTA_KODU,ULKE)
 VALUES ('1', 'ORHANGAZI' , 'ESENTEPE' , '5' , 'TOKAT', '60100' , 'TURKIYE');

 INSERT INTO KUTUPHANE(KUTUPHANE_NO, ADRES_NO,KUTUPHANE_ISMI,ACIKLAMA)
 VALUES ('1', '1', 'MERKEZ', 'MERKEZ KUTUPHANE');

 INSERT INTO EMANET (EMANET_NO,ISBN,UYE_NO,EMANET_TARIHI, TESLIM_TARIHI)
 VALUES( '1', '6055937515' ,'1', '1', '2009.10.12', '2009.10.17');

 INSERT INTO KITAPLAR (ISBN,KITAP_ADI,YAYIN_TARIHI,S_SAYISI)
 VALUES('6053950899', 'TURK EGITIM TARIHI', '2010.01.01','262');

 INSERT INTO YAZARLAR(YAZAR_NO,,YAZAR_ADI,YAZAR_SOYADI)
 VALUES ('1','TURGUT','OZSEVEN');

 INSERT INTO KATEGORI(KATEGORI_NO,KATEGORI_ADI)
 VALUES('1','BILGISAYAR');

 INSERT INTO KITAP_KUTUPHANE(KUTUPHANE_NO,MIKTAR)
 VALUES('1','6055937515','3');

 INSERT INTO KITAP_KATEGORI( ISBN,KATEGORI_NO)
 VALUES('6055937515','1');

 INSERT INTO KITAP_YAZAR(ISBN,YAZAR_NO)
 VALUES ('6055937515','2');

 UPDATE UYELER SET UYE_ADI='SELMA' WHERE UYE_NO=1;
 UPDATE ADRESLER SET CADDE='TALAS' WHERE ADRES_NO=1;
 UPDATE KUTUPHANE SET KUTUPHANE_ISMI='BUYUKSEHIR KUTUPHANE' WHERE KUTUPHANE_NO=1;
 UPDATE EMANET SET EMANET_TARIHI='2009.10.15' WHERE EMANET_NO=1;
 UPDATE KITAPLAR SET KITAP_ADI='TURK EGITIM TARIHI' WHERE ISBN=6053950899);
 UPDATE YAZARLAR SET YAZAR_ADI='ALI' WHERE YAZAR_NO=1;
UPDATE KATEGORI SET KATEGORI_ADI='BIYOLOJI' WHERE KATEGORI_NO=1;
UPDATE KITAPKUTUPHANE SET miktar='4' WHERE kutuphane_no=1; 
UPDATE KITAPKATEGORI SET KATEGORI_NO='2' WHERE ISBN=605593715;
UPDATE KITAP_YAZAR SET ISBN='605593716' WHERE YAZAR_NO=2;


	DELETE FROM  UYELER  WHERE UYE_NO=1;
	DELETE FROM  ADRESLER  WHERE ADRES_NO=1
	DELETE FROM  EMANET  WHERE EMANET_NO=1
	DELETE FROM KUTUPHANE   WHERE KUTUPHANE_NO=1
	DELETE FROM  KITAPLAR  WHERE ISBN=6053950899
	DELETE FROM YAZARLAR   WHERE YAZAR_NO=1
	DELETE FROM  KATEGORI  WHERE KATEGORI_NO=1
	DELETE FROM  KITAP_KUTUPHANE  WHERE KUTUPHANE_NO=1
	DELETE FROM  KITAP_KATEGORI  WHERE ISBN=605593715
	DELETE FROM KITAP_YAZAR   WHERE YAZAR_NO=2


	/* 3.ALISTIRMA ARTAN SIRADA LISTELEME*/

	SELECT *FROM UYELER ORDER BY UYE_NO ASC;

	/* 4.ALISTIRMA OCAK 2023TEN SONRA AKINAN KITAPLAR*/

	SELECT *FROM KITAPLAR
	WHERE EMANET_TARIHI > '01.01.2023' ;


	/* 5.ALISTIRMA KAYSERÝDE IKAMET EDIP,NO.SUNDA 6 ÝCEREN UYELER */

	SELECT *FROM UYELER 
	WHERE SEHIR = 'KAYSERI'  AND TELEFON LIKE '%6%' ;

	/* 6.ALISTIRMA TESLIM TARIHI BIR AYDAN AZ KALAN KITAPLAR */

	SELECT *FROM KITAPLAR 
	WHERE DATEDIFF(CURDATE(),TESLIM_TARIHI) < 30 ;

	/*7.ALISTIRMA */

	SELECT SUBSTRING(AD, 1,1) + SUBSTRING(SOYAD, 1,5) AS BIRLESIK_AD
	FROM UYELER WHERE LEN(SOYAD) >5
	ORDER BY BIRLESIK_AD ASC;
	
	
	/* 8.ALISTIRMA*/
	 SELECT DISTINCT SEHIR FROM UYELER 
	 ORDER BY SEHIR ASC;

	 /* 9.ALISTIRMA */

	 SELECT COUNT(*) AS EMANET_SAYISI
	 FROM EMANET
	 WHERE YEAR (EMANET_TARIHI)=2020;

	 /*10.ALISTIRMA*/

	 SELECT E.* FROM EMANET E
INNER JOIN KUTUPHANE K ON E.KUTUPHANE_NO = K.KUTUPHANE_NO
WHERE K.KUTUPHANE_ADI = 'KAYSERI BELEDIYESI MERKEZ KUTUPHANESI' 
AND DATEDIFF(MONTH, E.EMANET_TARIHI, E.TESLIM_TARIHI) > 6;


/*11.ALISTIRMA */
SELECT COUNT(*) AS ESKISEHIRDE_YASAYAN_UYE_SAYISI
FROM UYELER
WHERE SEHIR = 'ESKISEHIR';

/*12.ALISTIRMA*/

SELECT YAZARLAR
FROM KITAPLAR
INNER JOIN YAZARLAR ON KITAPLAR.YAZAR_NO = YAZARLAR.YAZAR_ID
WHERE DATEDIFF(YEAR, KITAPLAR.YAYIN_TARIHI, GETDATE()) > 3;

/*13.ALISTIRMA */

SELECT KITAP_NO, 
       MIN(DATEDIFF(DAY, EMANET_TARIHI, TESLIM_TARIHI)) AS EN_KISA_SURE,
       MAX(DATEDIFF(DAY, EMANET_TARIHI, TESLIM_TARIHI)) AS EN_UZUN_SURE
FROM EMANET
GROUP BY KITAP_NO ;

/*14.ALISTIRMA*/

SELECT UYELER.UYE_ADI, UYELER.UYE_SOYADI, EMANET.KITAP_ADI
FROM EMANET
INNER JOIN UYELER ON EMANET.UYE_NO = UYELER.UYE_NO;
